/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.senai.sp.jandira.gui;

import br.senai.sp.jandira.dao.EspecialidadeDAO;
import br.senai.sp.jandira.dao.PlanoDeSaudeDao;
import javax.swing.JTable;

/**
 *
 * @author 22282216
 */
public class PanelPlanoDeSaude extends javax.swing.JPanel {

    /**
     * Creates new form PanelPlanoDeSaude
     */
    public PanelPlanoDeSaude() {
        initComponents();
        PlanoDeSaudeDao.criarListaDePlanos();
        preencherTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPlanosDeSaude = new javax.swing.JScrollPane();
        tablePlanos = new javax.swing.JTable();
        buttonPlanosNovo = new javax.swing.JButton();
        buttonPlanosEditar = new javax.swing.JButton();
        buttonPlanosExcluir = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lista de Planos:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14), new java.awt.Color(255, 0, 0))); // NOI18N
        setPreferredSize(new java.awt.Dimension(790, 230));
        setVerifyInputWhenFocusTarget(false);
        setLayout(null);

        scrollPlanosDeSaude.setMinimumSize(new java.awt.Dimension(60, 80));
        scrollPlanosDeSaude.setPreferredSize(new java.awt.Dimension(300, 80));

        tablePlanos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollPlanosDeSaude.setViewportView(tablePlanos);

        add(scrollPlanosDeSaude);
        scrollPlanosDeSaude.setBounds(30, 30, 720, 120);

        buttonPlanosNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/imagens/mais (1).png"))); // NOI18N
        buttonPlanosNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPlanosNovoActionPerformed(evt);
            }
        });
        add(buttonPlanosNovo);
        buttonPlanosNovo.setBounds(730, 180, 50, 40);

        buttonPlanosEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/imagens/ferramenta-lapis.png"))); // NOI18N
        add(buttonPlanosEditar);
        buttonPlanosEditar.setBounds(670, 180, 50, 40);

        buttonPlanosExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/imagens/cancelar (1).png"))); // NOI18N
        add(buttonPlanosExcluir);
        buttonPlanosExcluir.setBounds(610, 180, 50, 40);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonPlanosNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPlanosNovoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonPlanosNovoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonPlanosEditar;
    private javax.swing.JButton buttonPlanosExcluir;
    private javax.swing.JButton buttonPlanosNovo;
    private javax.swing.JScrollPane scrollPlanosDeSaude;
    private javax.swing.JTable tablePlanos;
    // End of variables declaration//GEN-END:variables

private void preencherTabela() {

        tablePlanos.setModel(PlanoDeSaudeDao.getTabelaPlanos());
        ajustarTabela();

    }

    private void ajustarTabela() {

        //Impedir que o user mecha nas colunas
        tablePlanos.getTableHeader().setReorderingAllowed(false);

        //bloqueiar a edição de células da tabela
        tablePlanos.setDefaultEditor(Object.class, null);

        //definir a largura das colunas
        tablePlanos.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tablePlanos.getColumnModel().getColumn(0).setPreferredWidth(100);
        tablePlanos.getColumnModel().getColumn(1).setPreferredWidth(154);
        tablePlanos.getColumnModel().getColumn(2).setPreferredWidth(154);
        tablePlanos.getColumnModel().getColumn(3).setPreferredWidth(154);
        tablePlanos.getColumnModel().getColumn(4).setPreferredWidth(154);

    }

}
